apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: oaztssq34-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-132395bb9d.fyb6.p3.openshiftapps.com/rhtap/rhtap-qe:647932e35b1f5edfd0146af98031b4db5bcc20a5@sha256:e37d7aa627d7d548de88456d37e436901eb0ec50a0085cf57a264a977a4c2043
          name: container-image
